"use client";
import { TrendingUp, Activity, Award, CheckCircle2, ArrowRight } from "lucide-react";
import { Reveal, SectionHeading } from "../home/shared";
import { motion } from "framer-motion";

const TRENDS_DATA = [
  { sector: "Artificial Intelligence", growth: "+54%", value: 85, color: "from-teal-400 to-teal-650" },
  { sector: "CleanTech & Energy", growth: "+38%", value: 65, color: "from-teal-500 to-teal-700" },
  { sector: "FinTech", growth: "+22%", value: 45, color: "from-teal-600 to-teal-800" },
  { sector: "DeepTech & Robotics", growth: "+18%", value: 38, color: "from-emerald-500 to-teal-600" },
];

const RECENT_ACTIVITIES = [
  {
    id: 1,
    type: "match",
    text: "EcoVolt (CleanTech) matched with Sequoia Capital",
    detail: "Mandate compatibility score: 98%",
    time: "2 min ago",
  },
  {
    id: 2,
    type: "challenge",
    text: "Mayo Alliance diagnostic challenge received 12 bids",
    detail: "Top shortlist generated by AI vetting engine",
    time: "15 min ago",
  },
  {
    id: 3,
    type: "grant",
    text: "Standard Chartered approved pilot funding for Optima AI",
    detail: "$175,000 POC agreement escrow initiated",
    time: "32 min ago",
  },
  {
    id: 4,
    type: "match",
    text: "Aura Cyber (Security) matched with Andreessen Horowitz",
    detail: "Seed ticket routing completed",
    time: "1 hour ago",
  },
];

export default function MetricsSection() {
  return (
    <section className="relative py-24 px-4 bg-slate-50 dark:bg-[#060a0f] overflow-hidden">
      {/* Subtle backgrounds */}
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,rgba(20,184,166,0.02),transparent_50%)] pointer-events-none" />

      <div className="max-w-6xl mx-auto">
        <Reveal>
          <SectionHeading
            label="Live Platform Activity"
            title={
              <>
                Ecosystem Insights <span className="text-teal-500">& Trends</span>
              </>
            }
            sub="Our AI constantly monitors matching pipelines, capital allocation trends, and corporate challenge outcomes."
          />
        </Reveal>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-12">
          {/* Column 1: Growth Trends */}
          <Reveal delay={100}>
            <div className="bg-white dark:bg-[#0b131a] border border-slate-200/50 dark:border-slate-800/85 rounded-[28px] p-6 md:p-8 shadow-xl shadow-teal-500/5 flex flex-col h-full">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-teal-500/10 dark:bg-teal-500/5 flex items-center justify-center text-[#14b8a6]">
                    <TrendingUp size={16} />
                  </div>
                  <h3 className="text-base font-bold text-slate-800 dark:text-slate-200">
                    Quarterly Sector Momentum
                  </h3>
                </div>
                <span className="text-[10px] font-bold text-teal-600 dark:text-teal-400 uppercase tracking-widest bg-teal-500/10 px-2.5 py-1 rounded-md">
                  Venture Flow
                </span>
              </div>

              <div className="flex-1 flex flex-col justify-center gap-5">
                {TRENDS_DATA.map((item, idx) => (
                  <div key={item.sector} className="space-y-2">
                    <div className="flex justify-between text-xs md:text-sm font-semibold text-slate-750 dark:text-slate-300">
                      <span>{item.sector}</span>
                      <span className="text-teal-600 dark:text-teal-400 font-bold">{item.growth} growth</span>
                    </div>
                    <div className="h-3 w-full bg-slate-100 dark:bg-slate-900 rounded-full overflow-hidden border border-slate-250/20 dark:border-slate-800/30">
                      <motion.div
                        initial={{ width: 0 }}
                        whileInView={{ width: `${item.value}%` }}
                        viewport={{ once: true }}
                        transition={{ duration: 1, ease: "easeOut", delay: idx * 0.1 }}
                        className={`h-full rounded-full bg-gradient-to-r ${item.color}`}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Reveal>

          {/* Column 2: Live Activity Ledger */}
          <Reveal delay={180}>
            <div className="bg-white dark:bg-[#0b131a] border border-slate-200/50 dark:border-slate-800/85 rounded-[28px] p-6 md:p-8 shadow-xl shadow-teal-500/5 flex flex-col h-full">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-2.5">
                  <div className="w-8 h-8 rounded-lg bg-teal-500/10 dark:bg-teal-500/5 flex items-center justify-center text-[#14b8a6]">
                    <Activity size={16} className="animate-pulse" />
                  </div>
                  <h3 className="text-base font-bold text-slate-800 dark:text-slate-200">
                    Live Match Ledger
                  </h3>
                </div>
                <div className="flex items-center gap-1.5 text-[10px] font-bold text-teal-600 dark:text-teal-400 uppercase tracking-widest bg-teal-500/10 px-2.5 py-1 rounded-md">
                  <span className="w-1.5 h-1.5 rounded-full bg-teal-500 animate-ping" />
                  <span>Real-Time Stream</span>
                </div>
              </div>

              <div className="flex-1 flex flex-col gap-4">
                {RECENT_ACTIVITIES.map((act) => (
                  <div
                    key={act.id}
                    className="flex gap-3.5 p-3 rounded-xl border border-slate-100 dark:border-slate-800/40 bg-slate-50/[0.3] dark:bg-slate-900/10 hover:border-teal-500/20 dark:hover:border-teal-500/10 transition-colors"
                  >
                    <div className="mt-0.5 w-5 h-5 rounded-md flex items-center justify-center text-teal-600 dark:text-teal-400 bg-teal-500/10 dark:bg-teal-500/5 flex-shrink-0">
                      {act.type === "match" && <CheckCircle2 size={12} />}
                      {act.type === "challenge" && <ArrowRight size={12} />}
                      {act.type === "grant" && <Award size={12} />}
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="text-xs md:text-sm font-semibold text-slate-850 dark:text-slate-200 truncate">
                        {act.text}
                      </div>
                      <div className="text-[10px] md:text-xs text-slate-400 dark:text-slate-500 mt-0.5 truncate">
                        {act.detail}
                      </div>
                    </div>
                    <span className="text-[10px] font-semibold text-slate-400 dark:text-slate-500 whitespace-nowrap self-start mt-0.5">
                      {act.time}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </Reveal>
        </div>
      </div>
    </section>
  );
}