import { EcosystemEvent } from '@/types/event';

export const MOCK_EVENTS: EcosystemEvent[] = [
  {
    id: 'event-001',
    organizerName: 'StarHub Labs',
    organizerLogoText: 'SH',
    organizerLogoColor: '#14b8a6',
    eventName: 'Founders Sprint Demo Day',
    eventBannerLabel: 'Demo Day',
    eventBannerTone: 'linear-gradient(135deg, #0f766e 0%, #14b8a6 48%, #0f172a 100%)',
    category: 'Demo Day',
    location: 'Cairo, Egypt',
    startsAt: '2026-07-18T09:00:00+03:00',
    endsAt: '2026-07-18T17:00:00+03:00',
    description:
      'A curated demo day for founders graduating from the StarHub sprint track. Startups pitch to operator angels, corporate innovation teams, and ecosystem mentors, then move into structured matching sessions.',
    awards: ['Fast-track investor matching', '$25,000 cloud credits', 'Pilot introductions with corporate partners'],
    registerUrl: 'https://example.com/starthub-demo-day',
    contactEmail: 'events@starthub.com',
    contactPhone: '+20 100 555 0188',
    contactPerson: 'Mariam Hassan',
  },
  {
    id: 'event-002',
    organizerName: 'Nile Angels Network',
    organizerLogoText: 'NA',
    organizerLogoColor: '#0f766e',
    eventName: 'Investor Office Hours',
    eventBannerLabel: 'Office Hours',
    eventBannerTone: 'linear-gradient(135deg, #0f172a 0%, #0f766e 52%, #22c55e 100%)',
    category: 'Investor Session',
    location: 'Online',
    startsAt: '2026-07-18T18:00:00+03:00',
    endsAt: '2026-07-18T20:00:00+03:00',
    description:
      'Private fifteen-minute office-hour slots for founders preparing seed rounds across MENA. Investors review traction, deck clarity, and next-step fundraising readiness.',
    registerUrl: 'https://example.com/investor-office-hours',
    contactEmail: 'officehours@nileangels.co',
    contactPerson: 'Nile Angels Programs Team',
  },
  {
    id: 'event-003',
    organizerName: 'Delta Ventures',
    organizerLogoText: 'DV',
    organizerLogoColor: '#2563eb',
    eventName: 'MENA SaaS Fundraising Clinic',
    eventBannerLabel: 'Fundraising Clinic',
    eventBannerTone: 'linear-gradient(135deg, #1d4ed8 0%, #14b8a6 58%, #111827 100%)',
    category: 'Workshop',
    location: 'The Greek Campus, Cairo',
    startsAt: '2026-07-24T11:00:00+03:00',
    endsAt: '2026-07-24T15:30:00+03:00',
    description:
      'A working session for B2B SaaS founders to pressure-test pipeline quality, expansion metrics, pricing signals, and the fundraising story behind their next round.',
    awards: ['Two founders selected for partner review', 'Pitch narrative review from Delta Ventures'],
    registerUrl: 'https://example.com/mena-saas-clinic',
    contactEmail: 'programs@deltaventures.io',
  },
  {
    id: 'event-004',
    organizerName: 'GreenPath Impact Fund',
    organizerLogoText: 'GP',
    organizerLogoColor: '#16a34a',
    eventName: 'Climate Tech Challenge Briefing',
    eventBannerLabel: 'Climate Briefing',
    eventBannerTone: 'linear-gradient(135deg, #14532d 0%, #16a34a 54%, #0f766e 100%)',
    category: 'Challenge Briefing',
    location: 'Online',
    startsAt: '2026-08-05T16:00:00+03:00',
    endsAt: '2026-08-05T17:30:00+03:00',
    description:
      'An open briefing for startups applying to GreenPath Impact Fund challenges. The session explains target sectors, evidence expectations, and the impact metrics reviewers will use.',
    awards: ['$75,000 pilot budget for selected teams', 'Impact measurement advisory'],
    registerUrl: 'https://example.com/climate-tech-briefing',
    contactEmail: 'apply@greenpathfund.com',
  },
  {
    id: 'event-005',
    organizerName: 'Atlas Fintech Fund',
    organizerLogoText: 'AF',
    organizerLogoColor: '#7c3aed',
    eventName: 'AI Product Compliance Workshop',
    eventBannerLabel: 'Compliance Workshop',
    eventBannerTone: 'linear-gradient(135deg, #4c1d95 0%, #7c3aed 48%, #14b8a6 100%)',
    category: 'Workshop',
    location: 'Dubai Internet City',
    startsAt: '2026-08-12T10:30:00+04:00',
    endsAt: '2026-08-12T14:00:00+04:00',
    description:
      'A practical workshop for AI and fintech teams preparing for regulated pilots. Operators map model risk, customer consent, audit trails, and partner approval workflows.',
    registerUrl: 'https://example.com/ai-compliance-workshop',
    contactEmail: 'team@atlasfintechfund.com',
    contactPhone: '+971 50 555 0142',
  },
  {
    id: 'event-006',
    organizerName: 'Founders Bridge Syndicate',
    organizerLogoText: 'FB',
    organizerLogoColor: '#be123c',
    eventName: 'Cross-border Fintech Sandbox',
    eventBannerLabel: 'Sandbox',
    eventBannerTone: 'linear-gradient(135deg, #881337 0%, #be123c 48%, #0f766e 100%)',
    category: 'Sandbox',
    location: 'Riyadh, Saudi Arabia',
    startsAt: '2026-09-02T09:30:00+03:00',
    endsAt: '2026-09-04T16:00:00+03:00',
    description:
      'A three-day sandbox for fintech infrastructure startups testing cross-border settlement, compliance tooling, and embedded finance workflows with regional operators.',
    awards: ['Sandbox certification report', 'Introductions to banking partners', '$40,000 implementation support'],
    registerUrl: 'https://example.com/fintech-sandbox',
    contactEmail: 'hello@foundersbridge.vc',
    contactPerson: 'Founders Bridge Deal Team',
  },
];

export function getEventById(id: string) {
  return MOCK_EVENTS.find((event) => event.id === id);
}