import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";

import "./globals.css";
import PreloaderWrapper from "@/components/preloader/PreloaderWrapper";
import { NotificationProvider } from "@/components/notificationSystem/NotificationProvider";
import { RestTransport } from "@/lib/notifiationSystem/transports/RestTransport";
import { NotificationBell } from "@/components/notificationSystem/NotificationBell";
import { ToastContainer } from "@/components/notificationSystem/ToastContainer";
import { NotificationCenter } from "@/components/notificationSystem/NotificationCenter";

export const metadata: Metadata = {
  title: "Starthub",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale} className="h-full antialiased">
      <body className="min-h-full overflow-x-hidden">
        <NextIntlClientProvider>
          <PreloaderWrapper>
            <NotificationProvider>
              {children}
              <NotificationBell />
              <ToastContainer />
            </NotificationProvider>
          </PreloaderWrapper>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}